export const availability = [
  347, 296, 294, 305, 346, 297, 272, 361, 321, 304, 350, 303, 333, 258, 325,
  314, 322, 364, 345, 352, 343, 363, 287, 340, 271, 263, 277, 356, 290, 268,
  289, 300, 284, 265, 317, 342, 282, 339, 329, 311, 261, 360, 280, 335, 257,
  286, 328, 279, 336, 318, 301, 338, 275, 308, 291, 359, 354, 349, 254, 293,
  298, 324, 256, 310, 357, 332, 331, 264, 353, 315, 307, 270, 25, 39, 42, 43,
  26, 27, 37, 45
];

export const schedule = [
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 5,
    dayOfYear: 25,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 1,
    timeStart: 6,
    dayOfYear: 25,
    lessonType: "ONLINE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 4,
    dayOfYear: 26,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 1,
    timeStart: 7,
    dayOfYear: 26,
    lessonType: "ONLINE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 5,
    dayOfYear: 290,
    lessonType: "ONLINE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 5,
    dayOfYear: 290,
    lessonType: "ONLINE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 5,
    dayOfYear: 297,
    lessonType: "ONLINE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 5,
    dayOfYear: 304,
    lessonType: "ONLINE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 5,
    dayOfYear: 311,
    lessonType: "ONLINE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 5,
    dayOfYear: 318,
    lessonType: "ONLINE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 5,
    dayOfYear: 325,
    lessonType: "ONLINE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 5,
    dayOfYear: 332,
    lessonType: "ONLINE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 5,
    dayOfYear: 339,
    lessonType: "ONLINE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 5,
    dayOfYear: 346,
    lessonType: "ONLINE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 5,
    dayOfYear: 353,
    lessonType: "ONLINE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 5,
    dayOfYear: 359,
    lessonType: "ONLINE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 5,
    dayOfYear: 360,
    lessonType: "ONLINE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 6,
    dayOfYear: 290,
    lessonType: "ONLINE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 6,
    dayOfYear: 297,
    lessonType: "ONLINE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 6,
    dayOfYear: 304,
    lessonType: "ONLINE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 6,
    dayOfYear: 311,
    lessonType: "ONLINE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 6,
    dayOfYear: 318,
    lessonType: "ONLINE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 6,
    dayOfYear: 325,
    lessonType: "ONLINE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 6,
    dayOfYear: 332,
    lessonType: "ONLINE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 6,
    dayOfYear: 339,
    lessonType: "ONLINE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 6,
    dayOfYear: 346,
    lessonType: "ONLINE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 6,
    dayOfYear: 353,
    lessonType: "ONLINE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 6,
    dayOfYear: 360,
    lessonType: "ONLINE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 7,
    dayOfYear: 289,
    lessonType: "LECTURE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 7,
    dayOfYear: 296,
    lessonType: "LECTURE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 7,
    dayOfYear: 297,
    lessonType: "ONLINE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 7,
    dayOfYear: 303,
    lessonType: "LECTURE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 7,
    dayOfYear: 304,
    lessonType: "ONLINE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 7,
    dayOfYear: 310,
    lessonType: "LECTURE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 7,
    dayOfYear: 311,
    lessonType: "ONLINE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 7,
    dayOfYear: 317,
    lessonType: "LECTURE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 7,
    dayOfYear: 318,
    lessonType: "ONLINE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 7,
    dayOfYear: 324,
    lessonType: "LECTURE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 7,
    dayOfYear: 325,
    lessonType: "ONLINE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 7,
    dayOfYear: 331,
    lessonType: "LECTURE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 7,
    dayOfYear: 332,
    lessonType: "ONLINE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 7,
    dayOfYear: 338,
    lessonType: "LECTURE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 7,
    dayOfYear: 339,
    lessonType: "ONLINE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 7,
    dayOfYear: 345,
    lessonType: "LECTURE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 7,
    dayOfYear: 346,
    lessonType: "ONLINE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 7,
    dayOfYear: 353,
    lessonType: "ONLINE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 7,
    dayOfYear: 359,
    lessonType: "ONLINE",
  },
  {
    name: "Технологии программирования",
    subgroupNumber: 0,
    timeStart: 7,
    dayOfYear: 360,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 23,
    timeStart: 6,
    dayOfYear: 254,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 23,
    timeStart: 6,
    dayOfYear: 261,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 23,
    timeStart: 6,
    dayOfYear: 268,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 23,
    timeStart: 6,
    dayOfYear: 275,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 23,
    timeStart: 6,
    dayOfYear: 282,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 23,
    timeStart: 6,
    dayOfYear: 289,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 23,
    timeStart: 6,
    dayOfYear: 296,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 23,
    timeStart: 6,
    dayOfYear: 303,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 23,
    timeStart: 6,
    dayOfYear: 310,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 23,
    timeStart: 6,
    dayOfYear: 317,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 23,
    timeStart: 6,
    dayOfYear: 324,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 23,
    timeStart: 6,
    dayOfYear: 331,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 23,
    timeStart: 6,
    dayOfYear: 338,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 23,
    timeStart: 6,
    dayOfYear: 345,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 23,
    timeStart: 6,
    dayOfYear: 352,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 23,
    timeStart: 6,
    dayOfYear: 359,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 1,
    timeStart: 6,
    dayOfYear: 258,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 1,
    timeStart: 6,
    dayOfYear: 265,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 1,
    timeStart: 6,
    dayOfYear: 272,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 1,
    timeStart: 6,
    dayOfYear: 279,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 1,
    timeStart: 6,
    dayOfYear: 286,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 1,
    timeStart: 6,
    dayOfYear: 293,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 1,
    timeStart: 6,
    dayOfYear: 300,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 1,
    timeStart: 6,
    dayOfYear: 307,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 1,
    timeStart: 6,
    dayOfYear: 314,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 1,
    timeStart: 6,
    dayOfYear: 321,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 1,
    timeStart: 6,
    dayOfYear: 328,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 1,
    timeStart: 6,
    dayOfYear: 335,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 1,
    timeStart: 6,
    dayOfYear: 342,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 1,
    timeStart: 6,
    dayOfYear: 349,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 1,
    timeStart: 6,
    dayOfYear: 356,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 1,
    timeStart: 6,
    dayOfYear: 363,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 4,
    timeStart: 7,
    dayOfYear: 279,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 4,
    timeStart: 7,
    dayOfYear: 286,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 4,
    timeStart: 7,
    dayOfYear: 293,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 4,
    timeStart: 7,
    dayOfYear: 300,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 4,
    timeStart: 7,
    dayOfYear: 307,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 4,
    timeStart: 7,
    dayOfYear: 314,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 4,
    timeStart: 7,
    dayOfYear: 321,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 4,
    timeStart: 7,
    dayOfYear: 328,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 4,
    timeStart: 7,
    dayOfYear: 335,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 4,
    timeStart: 7,
    dayOfYear: 342,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 4,
    timeStart: 7,
    dayOfYear: 349,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 4,
    timeStart: 7,
    dayOfYear: 356,
    lessonType: "ONLINE",
  },
  {
    name: "Английский язык для IT-специалистов",
    subgroupNumber: 4,
    timeStart: 7,
    dayOfYear: 363,
    lessonType: "ONLINE",
  },
  {
    name: "Основы UX/UI дизайна",
    subgroupNumber: 0,
    timeStart: 6,
    dayOfYear: 256,
    lessonType: "ONLINE",
  },
  {
    name: "Основы UX/UI дизайна",
    subgroupNumber: 0,
    timeStart: 6,
    dayOfYear: 263,
    lessonType: "ONLINE",
  },
  {
    name: "Основы UX/UI дизайна",
    subgroupNumber: 0,
    timeStart: 6,
    dayOfYear: 270,
    lessonType: "ONLINE",
  },
  {
    name: "Основы UX/UI дизайна",
    subgroupNumber: 0,
    timeStart: 6,
    dayOfYear: 277,
    lessonType: "ONLINE",
  },
  {
    name: "Основы UX/UI дизайна",
    subgroupNumber: 0,
    timeStart: 6,
    dayOfYear: 284,
    lessonType: "ONLINE",
  },
  {
    name: "Основы UX/UI дизайна",
    subgroupNumber: 0,
    timeStart: 6,
    dayOfYear: 291,
    lessonType: "ONLINE",
  },
  {
    name: "Основы UX/UI дизайна",
    subgroupNumber: 0,
    timeStart: 6,
    dayOfYear: 298,
    lessonType: "ONLINE",
  },
  {
    name: "Основы UX/UI дизайна",
    subgroupNumber: 0,
    timeStart: 6,
    dayOfYear: 305,
    lessonType: "ONLINE",
  },
  {
    name: "Основы UX/UI дизайна",
    subgroupNumber: 0,
    timeStart: 6,
    dayOfYear: 333,
    lessonType: "ONLINE",
  },
  {
    name: "Основы UX/UI дизайна",
    subgroupNumber: 0,
    timeStart: 6,
    dayOfYear: 340,
    lessonType: "ONLINE",
  },
  {
    name: "Основы UX/UI дизайна",
    subgroupNumber: 0,
    timeStart: 6,
    dayOfYear: 347,
    lessonType: "ONLINE",
  },
  {
    name: "Основы UX/UI дизайна",
    subgroupNumber: 0,
    timeStart: 6,
    dayOfYear: 354,
    lessonType: "ONLINE",
  },
  {
    name: "Основы UX/UI дизайна",
    subgroupNumber: 0,
    timeStart: 6,
    dayOfYear: 361,
    lessonType: "ONLINE",
  },
  {
    name: "Основы UX/UI дизайна",
    subgroupNumber: 0,
    timeStart: 7,
    dayOfYear: 256,
    lessonType: "ONLINE",
  },
  {
    name: "Основы UX/UI дизайна",
    subgroupNumber: 0,
    timeStart: 7,
    dayOfYear: 263,
    lessonType: "ONLINE",
  },
  {
    name: "Основы UX/UI дизайна",
    subgroupNumber: 0,
    timeStart: 7,
    dayOfYear: 270,
    lessonType: "ONLINE",
  },
  {
    name: "Основы UX/UI дизайна",
    subgroupNumber: 0,
    timeStart: 7,
    dayOfYear: 277,
    lessonType: "ONLINE",
  },
  {
    name: "Основы UX/UI дизайна",
    subgroupNumber: 0,
    timeStart: 7,
    dayOfYear: 284,
    lessonType: "ONLINE",
  },
  {
    name: "Основы UX/UI дизайна",
    subgroupNumber: 0,
    timeStart: 7,
    dayOfYear: 291,
    lessonType: "ONLINE",
  },
  {
    name: "Основы UX/UI дизайна",
    subgroupNumber: 0,
    timeStart: 7,
    dayOfYear: 298,
    lessonType: "ONLINE",
  },
  {
    name: "Основы UX/UI дизайна",
    subgroupNumber: 0,
    timeStart: 7,
    dayOfYear: 305,
    lessonType: "ONLINE",
  },
  {
    name: "Основы UX/UI дизайна",
    subgroupNumber: 0,
    timeStart: 7,
    dayOfYear: 333,
    lessonType: "ONLINE",
  },
  {
    name: "Основы UX/UI дизайна",
    subgroupNumber: 0,
    timeStart: 7,
    dayOfYear: 340,
    lessonType: "ONLINE",
  },
  {
    name: "Основы UX/UI дизайна",
    subgroupNumber: 0,
    timeStart: 7,
    dayOfYear: 347,
    lessonType: "ONLINE",
  },
  {
    name: "Основы UX/UI дизайна",
    subgroupNumber: 0,
    timeStart: 7,
    dayOfYear: 354,
    lessonType: "ONLINE",
  },
  {
    name: "Основы UX/UI дизайна",
    subgroupNumber: 0,
    timeStart: 7,
    dayOfYear: 361,
    lessonType: "ONLINE",
  },
  {
    name: "Основы теории и методологии дизайна",
    subgroupNumber: 0,
    timeStart: 2,
    dayOfYear: 280,
    lessonType: "ONLINE",
  },
  {
    name: "Основы теории и методологии дизайна",
    subgroupNumber: 0,
    timeStart: 2,
    dayOfYear: 287,
    lessonType: "ONLINE",
  },
  {
    name: "Основы теории и методологии дизайна",
    subgroupNumber: 0,
    timeStart: 2,
    dayOfYear: 294,
    lessonType: "ONLINE",
  },
  {
    name: "Основы теории и методологии дизайна",
    subgroupNumber: 0,
    timeStart: 2,
    dayOfYear: 301,
    lessonType: "ONLINE",
  },
  {
    name: "Основы теории и методологии дизайна",
    subgroupNumber: 0,
    timeStart: 2,
    dayOfYear: 308,
    lessonType: "ONLINE",
  },
  {
    name: "Основы теории и методологии дизайна",
    subgroupNumber: 0,
    timeStart: 2,
    dayOfYear: 315,
    lessonType: "ONLINE",
  },
  {
    name: "Основы теории и методологии дизайна",
    subgroupNumber: 0,
    timeStart: 2,
    dayOfYear: 322,
    lessonType: "ONLINE",
  },
  {
    name: "Основы теории и методологии дизайна",
    subgroupNumber: 0,
    timeStart: 2,
    dayOfYear: 329,
    lessonType: "ONLINE",
  },
  {
    name: "Основы теории и методологии дизайна",
    subgroupNumber: 0,
    timeStart: 2,
    dayOfYear: 336,
    lessonType: "ONLINE",
  },
  {
    name: "Основы теории и методологии дизайна",
    subgroupNumber: 0,
    timeStart: 2,
    dayOfYear: 343,
    lessonType: "ONLINE",
  },
  {
    name: "Основы теории и методологии дизайна",
    subgroupNumber: 0,
    timeStart: 3,
    dayOfYear: 280,
    lessonType: "ONLINE",
  },
  {
    name: "Основы теории и методологии дизайна",
    subgroupNumber: 0,
    timeStart: 3,
    dayOfYear: 287,
    lessonType: "ONLINE",
  },
  {
    name: "Основы теории и методологии дизайна",
    subgroupNumber: 0,
    timeStart: 3,
    dayOfYear: 294,
    lessonType: "ONLINE",
  },
  {
    name: "Основы теории и методологии дизайна",
    subgroupNumber: 0,
    timeStart: 3,
    dayOfYear: 301,
    lessonType: "ONLINE",
  },
  {
    name: "Основы теории и методологии дизайна",
    subgroupNumber: 0,
    timeStart: 3,
    dayOfYear: 308,
    lessonType: "ONLINE",
  },
  {
    name: "Основы теории и методологии дизайна",
    subgroupNumber: 0,
    timeStart: 3,
    dayOfYear: 315,
    lessonType: "ONLINE",
  },
  {
    name: "Основы теории и методологии дизайна",
    subgroupNumber: 0,
    timeStart: 3,
    dayOfYear: 322,
    lessonType: "ONLINE",
  },
  {
    name: "Основы теории и методологии дизайна",
    subgroupNumber: 0,
    timeStart: 3,
    dayOfYear: 329,
    lessonType: "ONLINE",
  },
  {
    name: "Основы теории и методологии дизайна",
    subgroupNumber: 0,
    timeStart: 3,
    dayOfYear: 336,
    lessonType: "ONLINE",
  },
  {
    name: "Основы теории и методологии дизайна",
    subgroupNumber: 0,
    timeStart: 3,
    dayOfYear: 343,
    lessonType: "ONLINE",
  },
  {
    name: "Основы теории и методологии дизайна",
    subgroupNumber: 0,
    timeStart: 6,
    dayOfYear: 257,
    lessonType: "ONLINE",
  },
  {
    name: "Основы теории и методологии дизайна",
    subgroupNumber: 0,
    timeStart: 6,
    dayOfYear: 264,
    lessonType: "ONLINE",
  },
  {
    name: "Основы теории и методологии дизайна",
    subgroupNumber: 0,
    timeStart: 6,
    dayOfYear: 271,
    lessonType: "ONLINE",
  },
  {
    name: "Основы теории и методологии дизайна",
    subgroupNumber: 0,
    timeStart: 7,
    dayOfYear: 257,
    lessonType: "ONLINE",
  },
  {
    name: "Основы теории и методологии дизайна",
    subgroupNumber: 0,
    timeStart: 7,
    dayOfYear: 264,
    lessonType: "ONLINE",
  },
  {
    name: "Основы теории и методологии дизайна",
    subgroupNumber: 0,
    timeStart: 7,
    dayOfYear: 271,
    lessonType: "ONLINE",
  },
  {
    name: "QA / вебинар",
    subgroupNumber: 0,
    timeStart: 4,
    dayOfYear: 301,
    lessonType: "ONLINE",
  },
  {
    name: "QA / вебинар",
    subgroupNumber: 0,
    timeStart: 4,
    dayOfYear: 308,
    lessonType: "ONLINE",
  },
  {
    name: "QA / вебинар",
    subgroupNumber: 0,
    timeStart: 4,
    dayOfYear: 315,
    lessonType: "ONLINE",
  },
  {
    name: "QA / вебинар",
    subgroupNumber: 0,
    timeStart: 4,
    dayOfYear: 322,
    lessonType: "ONLINE",
  },
  {
    name: "QA / вебинар",
    subgroupNumber: 0,
    timeStart: 4,
    dayOfYear: 329,
    lessonType: "ONLINE",
  },
  {
    name: "QA / вебинар",
    subgroupNumber: 0,
    timeStart: 4,
    dayOfYear: 336,
    lessonType: "ONLINE",
  },
  {
    name: "QA / вебинар",
    subgroupNumber: 0,
    timeStart: 4,
    dayOfYear: 343,
    lessonType: "ONLINE",
  },
  {
    name: "QA / вебинар",
    subgroupNumber: 0,
    timeStart: 4,
    dayOfYear: 350,
    lessonType: "ONLINE",
  },
  {
    name: "QA / вебинар",
    subgroupNumber: 0,
    timeStart: 4,
    dayOfYear: 357,
    lessonType: "ONLINE",
  },
  {
    name: "QA / вебинар",
    subgroupNumber: 0,
    timeStart: 4,
    dayOfYear: 364,
    lessonType: "ONLINE",
  },
];
